DROP TABLE IF EXISTS Potilas CASCADE;
DROP TABLE IF EXISTS Laakari CASCADE;
DROP TABLE IF EXISTS Apteekki CASCADE;
DROP TABLE IF EXISTS Laake CASCADE;
DROP TABLE IF EXISTS Ainesosa CASCADE;
DROP TABLE IF EXISTS Laakkeenosa CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;